"""Configuration exports."""

from .nankai import (
    BreakRule,
    NANKAI_BREAK_RULES,
    NANKAI_CAMPUSES,
    NANKAI_DAY_END,
    NANKAI_DAY_START,
    NANKAI_DEFAULT_BREAK_MINUTES,
    NANKAI_DINNER_BREAK_END,
    NANKAI_DINNER_BREAK_START,
    NANKAI_HAS_EVENING_CLASSES,
    NANKAI_LONG_BREAK_MINUTES,
    NANKAI_SECTIONS_PER_DAY,
    NANKAI_WEEKDAYS,
    build_nankai_section_slots,
)

__all__ = [
    "BreakRule",
    "NANKAI_BREAK_RULES",
    "NANKAI_CAMPUSES",
    "NANKAI_DAY_END",
    "NANKAI_DAY_START",
    "NANKAI_DEFAULT_BREAK_MINUTES",
    "NANKAI_DINNER_BREAK_END",
    "NANKAI_DINNER_BREAK_START",
    "NANKAI_HAS_EVENING_CLASSES",
    "NANKAI_LONG_BREAK_MINUTES",
    "NANKAI_SECTIONS_PER_DAY",
    "NANKAI_WEEKDAYS",
    "build_nankai_section_slots",
]
